[package]
name = "airdrop2025-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
signature = "2.3.0-pre.4"
solana-client = "1.16.0"
solana-sdk = "1.16.0"
solana-program = "1.16.0"
borsh = "1.5.3"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
